---
title: "practica de dplyr"
author: "Alex Fernández"
format: html
toc: true
lang: es
theme: morph
---

# Introducción
Este documento presenta ejemplo de uso de las funciones del paquete dplyr

# Carga de paquetes

```{r}
#| label: carga-paquetes
#| message: false
#| warning: false

library(tidyverse)
library(knitr)
library(palmerpenguins)
```

# Carga datos

```{r}
#| label: carga-datos

delitos <- read_csv("estadisticaspoliciales2023.csv")
```

# select()

```{r}
#| label: select-01

# kable(penguins)

penguins |>
  select(species, sex, year) |>
  kable()
```

## Ejemplo 1

```{r}
#| label: select-02

# Cambio de nombre de columnas
penguins |>
  select(
    especie = species,
    sexo = sex,
    anio = year
  ) |>
  kable()
```

# filter ()

## Ejemplo 1

```{r}
#| label: filter-01

penguins |>
  filter(species == "Adelie", sex == "male", island == "Biscoe") |>
  kable()
```

## Ejemplo 2

```{r}
#| label: filter-02

# Pinguinos que viven en la isla Bisoce o en la isla Torgersen

penguins |>
  filter(island == "Biscoe" & island == "Torgersen") |> 
  kable()
```

## Ejemplo 3

```{r}
#| label: filter-03

# Robos cometidos en San Pedro de Montes de Oca

delitos |>
  filter(Delito == "ROBO" & Canton == "MONTES DE OCA" & Distrito == "SAN PEDRO") |>
  select(Delito, SubDelito, Victima, SubVictima, Canton, Distrito) |>
  kable()

```

# Ejemplo 4

```{r}
#| label: filter-04

# Pinguinos con NA en la columna de sexo
penguins |>
  filter(is.na(sex)) |>
  kable()
```
